#! /usr/bin/env ansible-playbook
- name: deploy 3 myapps
  hosts: "{{ host }}"
  force_handlers: true
  gather_facts: yes
  vars:
    ansible_host_key_checking: False
    ansible_ssh_host_key_checking: False
  roles:
    - role: deploy_myapps
