---
# tasks file for deploy_myapps
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  become: yes

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
  become: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: yes

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  become: yes

- name: Install Docker Module for Python
  pip:
    name: docker
  become: yes

- name: Install docker-compose Module for Python
  pip:
    name: docker-compose
  become: yes


- name: create dir for nginx
  file:
    dest: "/etc/nginx/"
    state: directory
  become: yes
  tags:
    - nginx

- name: copy nginx.conf
  become: yes
  copy:
    src: nginx.conf
    dest: "/etc/nginx/nginx.conf"
  tags:
    - nginx
- name: copy docker-compose
  template:
    src: docker-compose.yaml
    dest: "{{ service_dir }}"
  become: yes
  tags:
    - compose

- name: docker-compose up
  docker_compose:
    project_src: "{{ service_dir }}"
    state: present
  become: yes
  tags:
    - compose